blank_issues_enabled: false
contact_links:
  - name: ğŸŒˆ Support question or technical issue about ProjectNova
    url: https://projectnova.us/community/
    about: Use the forum or Discord server
  - name: ğŸ—¯ï¸ Negative feedback, complaints and demands
    url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    about: I'm taking those very seriously